on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - devel
      - main

name: CI - Test

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim:
          - '2.0.x'
          - 'stable'
          # - devel
        os:
          - ubuntu-latest
          # - windows-latest
          - macOS-latest

    name: '${{ matrix.nim }} (${{ matrix.os }})'
    steps:
      - uses: actions/checkout@v4
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v2
        with:
          use-nightlies: true
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -y
      - run: nimble test

